### ISSUE TITLE
Problem with the system setup :

### ISSUE THREAD

**Issue by dhled** [ScalABLE40/scalable_system_setup#1]
Here is the log from the wstool init src command :

ipa-led@ipa-led:~/ros-workspaces/scalable_ws$ wstool init src https://github.com/ScalABLE40/scalable_system_setup/raw/master/config/scalable.rosinstall
Using initial elements from: https://github.com/ScalABLE40/scalable_system_setup/raw/master/config/scalable.rosinstall
Writing /home/ipa-led/ros-workspaces/scalable_ws/src/.rosinstall
[system_setup/scalable_system_setup] Fetching git@github.com:ScalABLE40/scalable_system_setup.git (version None) to /home/ipa-led/ros-workspaces/scalable_ws/src/system_setup/scalable_system_setup
Cloning into '/home/ipa-led/ros-workspaces/scalable_ws/src/system_setup/scalable_system_setup'...
remote: Counting objects: 35, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 35 (delta 4), reused 8 (delta 3), pack-reused 25
Receiving objects: 100% (35/35), 5.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (11/11), done.
Checking connectivity... done.
[system_setup/scalable_system_setup] Done.
[skiros2/skiros2] Fetching git@github.com:RVMI/skiros2.git (version None) to /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2
Cloning into '/home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[skiros2/skiros2_std_lib] Fetching git@github.com:RVMI/skiros2_std_lib.git (version None) to /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_std_lib
Cloning into '/home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_std_lib'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[skiros2/skiros2_template_lib] Fetching git@github.com:RVMI/skiros2_template_lib.git (version None) to /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_template_lib
Cloning into '/home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_template_lib'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[skiros2/skiros2_test_lib] Fetching git@github.com:RVMI/skiros2_test_lib.git (version None) to /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_test_lib
Cloning into '/home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_test_lib'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exception caught during install: Error processing 'skiros2/skiros2' : [skiros2/skiros2] Checkout of git@github.com:RVMI/skiros2.git version None into /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2 failed.
Error processing 'skiros2/skiros2_std_lib' : [skiros2/skiros2_std_lib] Checkout of git@github.com:RVMI/skiros2_std_lib.git version None into /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_std_lib failed.
Error processing 'skiros2/skiros2_template_lib' : [skiros2/skiros2_template_lib] Checkout of git@github.com:RVMI/skiros2_template_lib.git version None into /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_template_lib failed.
Error processing 'skiros2/skiros2_test_lib' : [skiros2/skiros2_test_lib] Checkout of git@github.com:RVMI/skiros2_test_lib.git version None into /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_test_lib failed.

ERROR in config: Error processing 'skiros2/skiros2' : [skiros2/skiros2] Checkout of git@github.com:RVMI/skiros2.git version None into /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2 failed.
Error processing 'skiros2/skiros2_std_lib' : [skiros2/skiros2_std_lib] Checkout of git@github.com:RVMI/skiros2_std_lib.git version None into /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_std_lib failed.
Error processing 'skiros2/skiros2_template_lib' : [skiros2/skiros2_template_lib] Checkout of git@github.com:RVMI/skiros2_template_lib.git version None into /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_template_lib failed.
Error processing 'skiros2/skiros2_test_lib' : [skiros2/skiros2_test_lib] Checkout of git@github.com:RVMI/skiros2_test_lib.git version None into /home/ipa-led/ros-workspaces/scalable_ws/src/skiros2/skiros2_test_lib failed.

**Comment by frovida** [comment]
Right! I pushed a change, can you check if it works now?

**Comment by dhled** [comment]
Fixed !
